spring.kafka.bootstrap-servers=${BOOTSTRAP_SERVER_URL:localhost:9092}
consumer.topic=${ACSP_PROFILE_DELTA_TOPIC:acsp-profile-delta}
consumer.group-id=${GROUP_ID:acsp-profile-delta-consumer}
consumer.max-attempts=${MAX_ATTEMPTS:5}
consumer.backoff-delay=${BACKOFF_DELAY:1000}
consumer.concurrency=${CONCURRENT_LISTENER_INSTANCES:1}

management.endpoints.access.default=none
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true

api.api-key=${ACSP_PROFILE_API_KEY:testkey}
api.api-url=${API_LOCAL_URL:http://localhost:8099}

server.port=${PORT:8081}

# OpenTelemetry configuration
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics
